# Generated by Django 6.0.3 on 2026-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="code",
            field=models.CharField(default=12),
            preserve_default=False,
        ),
    ]
