# Generated by Django 6.0.3 on 2026-03-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_offer_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="discount",
            field=models.FloatField(default=0.2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="offer",
            name="code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="offer",
            name="description",
            field=models.CharField(max_length=255),
        ),
    ]
